import time
import sys
from datetime import datetime, timezone
from google import genai
from google.genai import types

if sys.platform.startswith("win"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

PROJECT_ID = "aiautomationplatform"
LOCATION = "us"
MODEL_ID = "gemini-3.8-flash"

print("=" * 70)
print(f"🚀 EXECUTING HIGH-END WORKLOAD ON VERTEX AI")
print(f"📌 Project:  {PROJECT_ID}")
print(f"🌍 Location: {LOCATION} (Vertex AI Multi-Region)")
print(f"🧠 Model:    {MODEL_ID}")
print(f"⏰ Timestamp: {datetime.now(timezone.utc).isoformat()}")
print("=" * 70)

# Initialize authenticated Vertex AI Client
client = genai.Client(
    vertexai=True,
    project=PROJECT_ID,
    location=LOCATION
)

high_end_prompt = """
ACT AS A GOOGLE DISTINGUISHED SOFTWARE ENGINEER & DISTRIBUTED SYSTEMS ARCHITECT.

Provide a comprehensive, production-grade architectural specification and implementation for a:
HIGH-FREQUENCY, LOCK-FREE, LOW-LATENCY DISTRIBUTED ORDER MATCHING & TRADING ENGINE (1,000,000 OPS/SEC).

Deliver:
1. Detailed Architecture Specification:
   - Ingress, Ring Buffers (Disruptor pattern), Sequence Assigners, Matching Core, Market Data Dispatchers.
   - P99.9 latency SLA budget (< 10 microseconds) with CPU pinning, NUMA awareness, and cache-line padding.

2. Production Python/C++ Algorithmic Core:
   - Full order book data structure with Price-Time Priority (FIFO) matching.
   - Limit Order, Market Order, and Cancel Order operations.
   - Zero-allocation memory pooling strategy.

3. Distributed Fault Tolerance & Persistence:
   - Raft state machine replication over RDMA / kernel-bypass networking.
   - Deterministic event sourcing and snapshotting mechanism.

4. Formal Complexity Analysis & Concurrency Proofs:
   - Proof of correctness against race conditions, ABA problems, and memory visibility order.
"""

print("\n[*] Dispatching high-compute request to Vertex AI Prediction Service...")
start_time = time.time()

response = client.models.generate_content(
    model=MODEL_ID,
    contents=high_end_prompt,
    config=types.GenerateContentConfig(
        temperature=0.2,
        max_output_tokens=4096,
    )
)

duration = time.time() - start_time

print("\n" + "=" * 70)
print("✅ VERTEX AI RESPONSE RECEIVED SUCCESSFULLY!")
print("=" * 70)
print(f"⏱️  Request Latency:         {duration:.2f} seconds")
print(f"🏷️  Model Reported:          {getattr(response, 'model_version', MODEL_ID)}")

if hasattr(response, "usage_metadata") and response.usage_metadata:
    usage = response.usage_metadata
    print(f"📥 Input Prompt Tokens:     {usage.prompt_token_count}")
    print(f"📤 Output Generated Tokens: {usage.candidates_token_count}")
    print(f"📊 Total Billable Tokens:   {usage.total_token_count}")

print("\n" + "-" * 35 + " RESPONSE PREVIEW " + "-" * 35)
print((response.text or "")[:1200] + "\n... [FULL CONTENT GENERATED] ...")
print("-" * 88)

# Save result to artifact file
out_path = "high_end_vertex_ai_task_output.md"
with open(out_path, "w", encoding="utf-8") as f:
    f.write(f"# High-End Distributed Systems Architecture\n")
    f.write(f"**Generated by:** `{MODEL_ID}` on Google Cloud Vertex AI\n")
    f.write(f"**GCP Project:** `{PROJECT_ID}`\n")
    f.write(f"**Execution Date:** `{datetime.now(timezone.utc).isoformat()}`\n")
    f.write(f"**Latency:** `{duration:.2f}s` | **Total Tokens:** `{usage.total_token_count if hasattr(response, 'usage_metadata') else 'N/A'}`\n\n")
    f.write("---\n\n")
    f.write(response.text or "")

print(f"\n[+] Full engineering blueprint saved to: {out_path}")
